name: Backend Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'Backend/**'
  pull_request:
    branches:
      - master
    paths:
      - 'Backend/**'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --prefix Backend
      - name: Run Lint
        run: npm run lint --prefix Backend

  build:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --prefix Backend
      - name: Build
        run: npm run build --prefix Backend
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_backend
          path: backend/build
      - name: Run tests
        run: npm run test --prefix Backend

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy to Fly.io
        run: |
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
