name: Frontend Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - master
    paths:
      - 'frontend/**'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --prefix frontend
      - name: Run Lint
        run: npm run lint --prefix frontend

  build:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --prefix frontend
      - name: Build
        run: npm run build --prefix frontend
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_frontend
          path: frontend/build

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy to Vercel
        run: |
          cd frontend
          vercel --prod --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
